[camera]

# 摄像头设备路径、数字索引或视频文件路径docs/videos/test4.mp4
source = "/dev/v4l/by-id/usb-170428-_Integrated_Webcam_HD-video-index0"

width = 1280
height = 640
fps = 30
fourcc = "MJPG"

# 视频回放
loop_video = true
realtime_playback = true
playback_fps = 30